## Additional tasks

In [1]:
import numpy as np

### 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [4]:
a = np.linspace(12, 24, num=12, endpoint=False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

### 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [9]:
def reshape(numpy_arr, shape_y): 
    shape_x = int(numpy_arr.shape[0] / shape_y)
    return numpy_arr.reshape(shape_x, shape_y)

derivatives = []
for shape_val in [1, 2, 3, 4, 6]:
    derivative = reshape(a, shape_val)
    derivatives.append(derivative)
    
    print('--------------------------')
    print(f'Shape: {derivative.shape}')
    print(f'Value:\n {derivative}')


--------------------------
Shape: (12, 1)
Value:
 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]
--------------------------
Shape: (6, 2)
Value:
 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
--------------------------
Shape: (4, 3)
Value:
 [[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
--------------------------
Shape: (3, 4)
Value:
 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
--------------------------
Shape: (2, 6)
Value:
 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


### 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [15]:
def reshape_rev(numpy_arr, shape_a, shape_b): 
    return numpy_arr.reshape(shape_a, shape_b)

derivatives_rev = []
for index, shape in enumerate([1, 2, 2, 3, 3]):
    derivative = reshape_rev(a, *((shape, -1) if (index & 1) else (-1, shape)))
    derivatives_rev.append(derivative)
    
    print('--------------------------')
    print(f'Shape: {derivative.shape}')
    print(f'Value:\n {derivative}')

--------------------------
Shape: (12, 1)
Value:
 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]
--------------------------
Shape: (2, 6)
Value:
 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------
Shape: (6, 2)
Value:
 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
--------------------------
Shape: (3, 4)
Value:
 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
--------------------------
Shape: (4, 3)
Value:
 [[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


### 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [27]:
test_arr = np.arange(0, 10).reshape(10, 1)
list(test_arr)

# Array of arrays is not flat

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

### 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [30]:
rand_arr = np.random.randn(3, 4)
flat_rand_arr = np.array(list(rand_arr.reshape(1, rand_arr.size)[0]))

print('Original array:')
print(rand_arr)
print(f'Shape: {rand_arr.shape}')
print('-------------------------')
print('Derivative array:')
print(flat_rand_arr)
print(f'Shape: {flat_rand_arr.shape}')
print('-------------------------')



Original array:
[[-0.4800837   1.86248917 -1.00187396 -0.36496315]
 [ 0.10609536  0.04483054  0.23431436  0.44950924]
 [-0.23309362 -0.20033492  0.39970181  0.73151243]]
Shape: (3, 4)
-------------------------
Derivative array:
[-0.4800837   1.86248917 -1.00187396 -0.36496315  0.10609536  0.04483054
  0.23431436  0.44950924 -0.23309362 -0.20033492  0.39970181  0.73151243]
Shape: (12,)
-------------------------


### 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [32]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [36]:
b = np.arange(20, 1, -2)
b = b.reshape(b.size, 1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

### 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [54]:
a = np.zeros((2, 2))
b = np.zeros((3, 2)) + 1
v = np.vstack((a, b))

print(f'Concatenated array:\n{v}\n')
print(f'Size: {v.size}')


Concatenated array:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Size: 10


### 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [64]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.transpose()
B = np.dot(A, At)

B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

### 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [76]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

### 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.


In [85]:
c = np.arange(0, 16)
np.random.shuffle(c)
c

array([10,  7,  0,  2,  5,  6, 15, 12,  4, 13, 14,  9,  1, 11,  8,  3])

### 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [93]:
c_square_matrix_size = int(c.size ** .5)
C = c.reshape(c_square_matrix_size, c_square_matrix_size)
D = B + (C * 10)
D_determinant = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)


print(f'Original  :\n{D}\n')
print(f'Deteminant: {D_determinant}\n')
print(f'Rank      : {D_rank}\n')
print(f'Inverted  : \n{D_inv}\n')


Original  :
[[105  84  23  52]
 [ 64 110 236 242]
 [ 63 216 289 302]
 [ 42 232 292 332]]

Deteminant: -64505399.99999988

Rank      : 4

Inverted  : 
[[ 0.00770602  0.00631761  0.00123587 -0.00693616]
 [ 0.00106317 -0.0147476   0.01563683 -0.00364063]
 [-0.0083962  -0.00356807  0.038132   -0.03077045]
 [ 0.00566681  0.01264452 -0.04462107  0.03349673]]



### 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [94]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv


array([[1, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 1, 0, 1]])

In [96]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,   2],
       [ 14,   6,  86,  12],
       [  4,  13, 149,   9],
       [ 32, 122,   8, 302]])